### ISSUE TITLE
server_testing_function

### ISSUE THREAD

**Issue by ADimoska** [MattSScott/basePlatformSOMAS#5]

**Comment by ADimoska** [comment]
#[89b4c52](https://github.com/MattSScott/basePlatformSOMAS/commit/89b4c52ca7796b4b9ca33403a4d219d8b931b180)
The issue is in the server_test.go Line 35. I got the error: The GetID() is not a method or field in baseAgent.Agent, then I tried other things that I hoped that could solve the problem but it was unsuccessful. I forgot to delete line 42 and the condition at line 35 is not correct.

**Comment by MattSScott** [comment]
resolved in #6
